### ISSUE TITLE
java.lang.UnsupportedOperationException: Unsupported Service: captioning

### ISSUE THREAD

**Issue by grilo341** [BrightcoveOS/android-player-samples#122]
java.lang.UnsupportedOperationException: Unsupported Service: captioning
	at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:602)
	at com.brightcove.player.controller.BrightcoveClosedCaptioningController.initCaptioningManager(BrightcoveClosedCaptioningController.java:426)
	at com.brightcove.player.controller.BrightcoveClosedCaptioningController.<init>(BrightcoveClosedCaptioningController.java:115)
	at com.brightcove.player.view.BaseVideoView.setEventEmitter(BaseVideoView.java:399)
	at com.brightcove.player.view.BaseVideoView.finishInitialization(BaseVideoView.java:337)
	at com.brightcove.player.view.BaseVideoView.onFinishInflate(BaseVideoView.java:326)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:867)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:389)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:548)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:533)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:966)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:533)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$53(RenderTask.java:659)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

how can i fix this?

**Comment by fanysoft** [comment]
same here 
java.lang.UnsupportedOperationException: Unsupported Service: captioning
	at com.android.layoutlib.bridge.android.BridgeContext.getSystemService(BridgeContext.java:627)
	at com.brightcove.player.controller.BrightcoveClosedCaptioningController.initCaptioningManager(BrightcoveClosedCaptioningController.java:429)
	at com.brightcove.player.controller.BrightcoveClosedCaptioningController.<init>(BrightcoveClosedCaptioningController.java:118)
	at com.brightcove.player.view.BaseVideoView.setEventEmitter(BaseVideoView.java:399)
	at com.brightcove.player.view.BaseVideoView.finishInitialization(BaseVideoView.java:337)
	at com.brightcove.player.view.BaseVideoView.onFinishInflate(BaseVideoView.java:326)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:867)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sergiomartinez4** [comment]
When does that happen?
How can I reproduce that?

**Comment by fanysoft** [comment]
in Android Studio - i have within layout 
  <com.brightcove.player.view.BrightcoveExoPlayerVideoView
        android:id="@+id/brightcove_video_view"
        android:layout_width="1000dp"
        android:layout_height="280dp"
        android:layout_gravity="center"
        android:orientation="horizontal" />
Preview failed, when I delete this object from layout - I can see preview correctly.

![screenshot_1](https://cloud.githubusercontent.com/assets/10332850/26683348/cdf478ac-46e3-11e7-9605-bc3a40786229.png)

**Comment by sergiomartinez4** [comment]
@fanysoft Thanks for reporting the problem and sharing the information.
We've added the issue on our backlog and it will be prioritize accordingly.

**Comment by BCjwhisenant** [comment]
Closing, outdated
