### ISSUE TITLE
BasicIMASampleApp crash with release variant

### ISSUE THREAD

**Issue by rslama** [BrightcoveOS/android-player-samples#143]
When I run BasicIMASampleApp project as release variant it crashed with:

java.lang.NoSuchMethodError: No super method setOnCompletionListener(Landroid/media/MediaPlayer$b;)V in class Landroid/widget/VideoView; or its super classes (declaration of 'android.widget.VideoView' appears in /system/framework/framework.jar:classes2.dex)
                                                       at com.brightcove.a.b.<init>(Unknown Source:21)
                                                       at com.brightcove.a.a.<init>(Unknown Source:211)
                                                       at com.brightcove.a.a.<init>(Unknown Source:6)
                                                       at com.brightcove.player.samples.ima.basic.MainActivity.a(Unknown Source:70)
                                                       at com.brightcove.player.samples.ima.basic.MainActivity.onCreate(Unknown Source:56)
                                                       at android.app.Activity.performCreate(Activity.java:6975)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                       at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

Possible reason is due to wrong proguard settings. I facing same issue after update ima&brightcove sdk to latest

**Comment by raajbcove** [comment]
This does not look like a ProGuard issue. However, you can try adding the following exclusion rule to see if it helps:

`-keep class com.brightcove.player.** { *; }`

**Comment by rslama** [comment]
@raajbcove unfortunate that doesn't work. And definitely that is Proguard issue.

**Comment by raajbcove** [comment]
@rslama The rule I gave you only excludes classes within the Brightcove SDK. What is the complete set of ProGuard rules you are using in your test? From the stacktrace you posted in your first comment, it appears that the standard android classes (android.media.MediaPlayer) are being obfuscated, which being used by Google IMA SDK. Please consider adding the following, if you haven't already:

`-keep class android.media.** { *; }`

**Comment by rslama** [comment]
I consider that and what works is follow rules:
-keep class android.media.** {*;}
-keep class com.android.** {*;}
but that is not what I mention as issue. Please try follow simple steps and u will see what a problem is:

// 1. Download the repository
>> git clone git@github.com:BrightcoveOS/android-player-samples.git
// 2. Assemble a release build
>> ./gradlew :brightcove-mediaplayer:BasicIMASampleApp:assembleRelease
// 3. Install and open the app. It’s crashing.
>> adb install brightcove-mediaplayer/BasicIMASampleApp/build/outputs/apk/BasicIMASampleApp-release.apk
// 4. launch BasicIMASampleApp

**Comment by raajbcove** [comment]
@rslama I am guessing that you are seeing more ProGuard failures in other parts of the release build, for ex Google IMA. The sample code provided in this repo are targeted towards demonstrating the various capabilities of the Brightcove SDK. Solving third party ProGuard issues is beyond the scope of this repo. 

That said, I did manage to run the BasicIMASampleApp in release mode after adding the following rules to exclude Google Play/Ad services classes/interfaces:
`
-dontwarn com.google.**
-dontwarn android.media.**

-keep class android.media.** { *; }
-keep class com.google.** { *; }
-keep interface com.google.** { *; }
`

**Comment by sergiomartinez4** [comment]
Please also add the following:
```
-keep class com.google.ads.interactivemedia.** { *; }
-keep interface com.google.ads.interactivemedia.** { *; }
```
