### ISSUE TITLE
brightcove keep crashing because of NPE

### ISSUE THREAD

**Issue by liauli** [BrightcoveOS/android-player-samples#151]
Hi Everyone!
recently I keep getting this kind of error:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.google.android.exoplayer2.SimpleExoPlayer.getPlayWhenReady()' on a null object reference
       at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.reportPlayerState(Unknown Source)
       at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.access$500(Unknown Source)
       at com.brightcove.player.display.ExoPlayerVideoDisplayComponent$9.onLoadError(Unknown Source)
       at com.google.android.exoplayer2.source.AdaptiveMediaSourceEventListener$EventDispatcher$4.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5546)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)`

I am not sure why and I don't know how to handle or prevent this crash. I keep getting it recently especially when the error event called. It will be easier if inside the brightcove have null checking for this. Can someone help me ? Thanks!

**Comment by BCjwhisenant** [comment]
Hello,
Can you give us some details?

What sample app are you running when you see this error?
Have you modified the sample, for example to load a different video?

Thanks!
