### ISSUE TITLE
androidx: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brightcove.player.util.LifecycleUtil.onActivityCreated(android.os.Bundle)' on a null object reference

### ISSUE THREAD

**Issue by mihaelaLo** [BrightcoveOS/android-player-samples#199]
Using the androidx appcompat dependency and BrightcovePlayerFragment, app crashes with the following NPE:

> java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brightcove.player.util.LifecycleUtil.onActivityCreated(android.os.Bundle)' on a null object reference
        at com.brightcove.player.appcompat.BrightcovePlayerFragment.onActivityCreated(BrightcovePlayerFragment.java:78)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2460)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1483)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3269)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
        at android.app.Activity.performStart(Activity.java:7157)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2937)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

Example: https://github.com/mihaelaLo/BrightcoveErrorApplication

**Comment by sergiomartinez4** [comment]
Hi @mihaelaLo, thanks for reporting this issue. 
We currently don't support androidx, but it's in our plans to do so. I will add this issue in our backlog to be considered when adding support for androidx.

**Comment by HasanElHefnawy** [comment]
Hi @sergiomartinez4, I have the same issue. Is there any update?

**Comment by BCjwhisenant** [comment]
Hello @HasanElHefnawy ,
AndroidX support is still on our roadmap, but we have not been able to implement support for it just yet.

**Comment by BCjwhisenant** [comment]
Closing, the SDK is now built with AndroidX libraries and support as of v6.10.0.

**Comment by liveHarshit** [comment]
@BCjwhisenant Thanks for the update. But I'm still getting the following error while extending `BrightcovePlayerFragment` to the fragment: 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.brightcove.player.util.LifecycleUtil.onActivityCreated(android.os.Bundle)' on a null object reference
```
With `"com.brightcove.player:android-appcompat-plugin:6.10.0"`
Any help?

**Comment by droider91** [comment]
@liveHarshit Did you solve this issue?

**Comment by HasanElHefnawy** [comment]
@droider91 Instead of using BrightcovePlayerFragment and baseVideoView, use androidx.fragment.app.Fragment and create an instance of BrightcoveExoPlayerVideoView.

**Comment by droider91** [comment]
Hello @HasanElHefnawy would you please refer any helping tutorial?

**Comment by HasanElHefnawy** [comment]
@droider91 in this [sample](https://github.com/BrightcoveOS/android-player-samples/blob/master/brightcove-exoplayer/AppCompatFragmentSampleApp/src/main/java/com/brightcove/player/samples/appcompat/fragment/MainFragment.java),

1. replace `BrightcovePlayerFragment` with `Fragment`.
2. replace `baseVideoView` with an instance of `BrightcoveExoPlayerVideoView`.
