### ISSUE TITLE
NotSerializableException: com.brightcove.player.captioning.PreviewThumbnailFormat

### ISSUE THREAD

**Issue by h-mubarak** [BrightcoveOS/android-player-samples#223]
brightcoveVersion = "6.8.0" and 6.13.3

Issue is happening when you load the video in the activity 
Log:
 ```
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.brightcove.player.model.Video)
        at android.os.Parcel.writeSerializable(Parcel.java:1786)
        at com.brightcove.player.model.Video.writeToParcel(Video.java:1067)
        at android.os.Parcel.writeParcelable(Parcel.java:1755)
        at android.os.Parcel.writeValue(Parcel.java:1661)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:801)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506)
        at android.os.Bundle.writeToParcel(Bundle.java:1181)
        at android.os.Parcel.writeBundle(Parcel.java:841)
        at android.content.Intent.writeToParcel(Intent.java:10199)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4859)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
        at android.app.Activity.startActivityForResult(Activity.java:4564)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4522)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4883)
        at android.app.Activity.startActivity(Activity.java:4851)
    
        at android.view.View.performClick(View.java:6886)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.io.NotSerializableException: com.brightcove.player.captioning.PreviewThumbnailFormat
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1233)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at java.util.ArrayList.writeObject(ArrayList.java:762)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1545)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at java.util.HashMap.internalWriteEntries(HashMap.java:1789)
        at java.util.HashMap.writeObject(HashMap.java:1366)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1545)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1597)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1558)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1481)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1227)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:347)
        at android.os.Parcel.writeSerializable(Parcel.java:1781)
        at com.brightcove.player.model.Video.writeToParcel(Video.java:1067) 
        at android.os.Parcel.writeParcelable(Parcel.java:1755) 
        at android.os.Parcel.writeValue(Parcel.java:1661) 
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:801) 
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1506) 
        at android.os.Bundle.writeToParcel(Bundle.java:1181) 
        at android.os.Parcel.writeBundle(Parcel.java:841) 
        at android.content.Intent.writeToParcel(Intent.java:10199) 
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4859) 
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617) 
        at android.app.Activity.startActivityForResult(Activity.java:4564) 
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767) 
        at android.app.Activity.startActivityForResult(Activity.java:4522) 
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754) 
        at android.app.Activity.startActivity(Activity.java:4883) 
        at android.app.Activity.startActivity(Activity.java:4851) 
        at android.view.View.performClick(View.java:6886) 
        at android.view.View$PerformClick.run(View.java:26083) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by BCjwhisenant** [comment]
Hello @h-mubarak,

I just tried to reproduce this problem in both the AppCompatFragmentSampleApp, and the ThumbnailScrubberSampleApp, and was unable to see the error you've posted here.

We have a developer forum [here](https://groups.google.com/forum/#!forum/brightcove-native-player-sdks), and we invite you to open a discussion of this problem there (the forum is monitored daily for new discussions; this issue list, much less so). Please include as much information as you have about where this problem is occurring. If possible, please include a video ID, account ID and policy key for retrieving the video.

Cheers!

**Comment by h-mubarak** [comment]
Hi BCjwhisenant,

Thanks for replying. The issue is happening with a particular video id. I can not share video information because of company policy.
I am wondering why `PreviewThumbnailFormat` class is not serialized. I have seen in the Brightcove sdk code.

I will post the issue in the developer forum.

Cheers

**Comment by BCjwhisenant** [comment]
Closing, this was posted to the developer forum. Please reopen this if you are still having issues.
