### ISSUE TITLE
Player showing poster but not playing video

### ISSUE THREAD

**Issue by droider91** [BrightcoveOS/android-player-samples#260]
I shipped the player in my production ready project but it is not working, while same classes are working in the demo project.

```
2022-06-21 17:34:01.999 10929-10929/com.test.app D/BlankFragment: response { source: Source{deliveryType: video/mpeg-dash, url: **************************************************************************************************************************************************************************************************************************************************************** requestToken: 394 video: Video{name: "07-Paul-Wilmott-Backup-The-Pain-and-Pleasure-of-Investing", sourceCollections: 1, cuePoints: 0} }
2022-06-21 17:34:01.999 10929-10929/com.test.app V/VideoPlaybackController: OnSourceSelectedListener
2022-06-21 17:34:02.000 10929-10929/com.test.app D/BlankFragment: didSelectSource { source: Source{deliveryType: video/mpeg-dash, url: **************************************************************************************************************************************************************************************************************************************************************** video: Video{name: "07-Paul-Wilmott-Backup-The-Pain-and-Pleasure-of-Investing", sourceCollections: 1, cuePoints: 0} }
2022-06-21 17:34:02.001 10929-10929/com.test.app D/BlankFragment: setSource { source: Source{deliveryType: video/mpeg-dash, url: **************************************************************************************************************************************************************************************************************************************************************** video: Video{name: "07-Paul-Wilmott-Backup-The-Pain-and-Pleasure-of-Investing", sourceCollections: 1, cuePoints: 0} }
2022-06-21 17:34:02.001 10929-10929/com.test.app V/ExoPlayer2VideoDisplay: ExoPlayerOnSetSourceListener
2022-06-21 17:34:02.001 10929-10929/com.test.app V/ExoPlayer2VideoDisplay: destroyPlayer: exoPlayer = null
2022-06-21 17:34:02.001 10929-10929/com.test.app V/ExoPlayer2VideoDisplay: openVideo: ***************************************************************************************************************************************************************************************************************************************************************
2022-06-21 17:34:02.001 10929-10929/com.test.app V/ExoPlayer2VideoDisplay: destroyPlayer: exoPlayer = null
2022-06-21 17:34:02.001 10929-10929/com.test.app V/ExoPlayer2VideoDisplay: createPlayer: *************************************************************************************************


E/com.brightcove.player.event.EventEmitterImpl@58e61c1: processEvent() threw a throwable.
    java.lang.NoSuchMethodError: No virtual method setParameters(Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector$Parameters;)V in class Lcom/google/android/exoplayer2/trackselection/DefaultTrackSelector; or its super classes (declaration of 'com.google.android.exoplayer2.trackselection.DefaultTrackSelector' appears in /data/app/~~MCh2rBbL4xnznUBH5tgjSw==/com.test.app-Ph_FvaFMw3hr4r1wiUJbMg==/base.apk!classes2.dex)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.updateTrackSelectorPeakBitrate(ExoPlayerVideoDisplayComponent.java:1962)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.initializePlayer(ExoPlayerVideoDisplayComponent.java:1005)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.createPlayer(ExoPlayerVideoDisplayComponent.java:993)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.openVideo(ExoPlayerVideoDisplayComponent.java:1054)
        at com.brightcove.player.display.VideoDisplayComponent.openCurrentVideoSource(VideoDisplayComponent.java:470)
        at com.brightcove.player.display.ExoPlayerVideoDisplayComponent$ExoPlayerOnSeekListener.processEvent(ExoPlayerVideoDisplayComponent.java:1168)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEventType(EventEmitterImpl.java:458)
        at com.brightcove.player.event.EventEmitterImpl.invokeListenersForEvent(EventEmitterImpl.java:429)
        at com.brightcove.player.event.EventEmitterImpl.access$300(EventEmitterImpl.java:42)
        at com.brightcove.player.event.EventEmitterImpl$1.handleMessage(EventEmitterImpl.java:74)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:257)
        at android.app.ActivityThread.main(ActivityThread.java:8218)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1015)

```
I am getting this error msg from brightcove.

My gradle config is

```
 implementation "com.brightcove.player:android-appcompat-plugin:6.18.1"
 implementation  "com.brightcove.player:exoplayer2:6.18.1"

    const val COMPILE_SDK = 30
    const val MIN_SDK = 21
    const val TARGET_SDK = 30

    /* Build/tooling */
    const val ANDROID_GRADLE_TOOLS = "3.5.1"
    const val BUILD_TOOLS = "30.0.2"
    const val BUILD_SCAN = "1.16"

```

**Comment by anhkieet** [comment]
Hi @droider91 Have you fixed this issue yet? I am having the same issue as you

**Comment by jrw95** [comment]
Hi @droider91 @anhkieet 
It doesn't sound as though the videos are a root cause here, if they're able to load and play in a sample app.
If these problems are occurring in your app code, but not in an SDK sample app, it would be necessary to provide some context around how you're loading the content, although to set expectations, we don't have a lot of bandwidth to debug application code.

**Comment by anhkieet** [comment]
@jrw95  Maybe I found the cause. There is another package using exoplayer2:2.18.1. Can I know if Brightcove Native SDK upgraded to this version?

**Comment by anhkieet** [comment]
I solved this issue by making sure exoplayer2 version consistent in the app

**Comment by jrw95** [comment]
Thanks for getting back to us.
