### ISSUE TITLE
Jetpack compose

### ISSUE THREAD

**Issue by fllaryora** [BrightcoveOS/android-player-samples#277]
Hi, I am trying to run BrightcoveOS with Jetpack compose in my fork:
[activityCompose](https://github.com/fllaryora/android-player-samples/tree/activityCompose)
But I can configure the activity Properly.
When I create the BrightcoveExoPlayerVideo, the inner event emitter is null.

` com...ayer.samples.compose.activity  E  FATAL EXCEPTION: main
                                                                                                    Process: com.brightcove.player.samples.compose.activity, PID: 2252
                                                                                                    java.lang.IllegalArgumentException: Must provide an EventEmitter.
                                                                                                    	at com.brightcove.player.event.AbstractComponent.<init>(AbstractComponent.java:45)
                                                                                                    	at com.brightcove.player.util.LifecycleUtil.<init>(LifecycleUtil.java:83)
                                                                                                    	at com.brightcove.player.samples.compose.activity.BrightcoveComponentActivity.initializeLifecycleUtil(BrightcoveComponentActivity.kt:50)
                                                                                                    	at com.brightcove.player.samples.compose.activity.MainActivity$onCreate$1$1$1$1.invoke(MainActivity.kt:25)
                                                                                                    	at com.brightcove.player.samples.compose.activity.MainActivity$onCreate$1$1$1$1.invoke(MainActivity.kt:25)
                                                                                                    	at com.brightcove.player.samples.compose.activity.ui.BrightcoveExoPlayerVideoKt$BrightcoveExoPlayerVideo$1$1.invoke(BrightcoveExoPlayerVideo.kt:30)
                                                                                                    	at com.brightcove.player.samples.compose.activity.ui.BrightcoveExoPlayerVideoKt$BrightcoveExoPlayerVideo$1$1.invoke(BrightcoveExoPlayerVideo.kt:22)
                                                                                                    	at androidx.compose.ui.viewinterop.ViewFactoryHolder.setFactory(AndroidView.android.kt:178)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:116)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$1.invoke(AndroidView.android.kt:113)
                                                                                                    	at androidx.compose.ui.viewinterop.AndroidView_androidKt$AndroidView$$inlined$ComposeNode$1.invoke(Composables.kt:254)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1559)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$createNode$2.invoke(Composer.kt:1557)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3450)
                                                                                                    	at androidx.compose.runtime.ComposerImpl$recordInsert$2.invoke(Composer.kt:3447)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:808)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:839)
                                                                                                    	at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:978)
                                                                                                    	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:519)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:140)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1060)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:182)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:202)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:138)
                                                                                                    	at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
                                                                                                    	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1147)
                                                                                                    	at android.view.View.dispatchAttachedToWindow(View.java:20479)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                                                                                                    	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:731)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
2023-05-08 10:25:43.646  2252-2252  AndroidRuntime          com...ayer.samples.compose.activity  E  	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

Is there anyone here good with Jetpack compose?
Thank you in advance.

**Comment by fllaryora** [comment]
I have good news.
I Could play a video, but I can enter full screen mode.

> 
> FATAL EXCEPTION: main
>                                                                                                     Process: com.brightcove.player.samples.compose.activity, PID: 17103
>                                                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.brightcove.player.controller.FullScreenController.isFullScreen()' on a null object reference
>                                                                                                     	at com.brightcove.player.view.BaseVideoView.isFullScreen(BaseVideoView.java:582)
>                                                                                                     	at com.brightcove.player.mediacontroller.buttons.FullScreenButtonController.getManagedState(FullScreenButtonController.java:99)
>                                                                                                     	at com.brightcove.player.mediacontroller.buttons.AbstractButtonController.syncStates(AbstractButtonController.java:216)
>                                                                                                     	at com.brightcove.player.mediacontroller.buttons.FullScreenButtonController.<init>(FullScreenButtonController.java:83)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.initializeButtons(BrightcoveMediaController.java:670)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.initializeControlBar(BrightcoveMediaController.java:733)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.initializeControlBar(BrightcoveMediaController.java:698)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.init(BrightcoveMediaController.java:282)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.<init>(BrightcoveMediaController.java:260)
>                                                                                                     	at com.brightcove.player.mediacontroller.BrightcoveMediaController.<init>(BrightcoveMediaController.java:248)
>                                                                                                     	at com.brightcove.player.view.BaseVideoView.setDefaultMediaController(BaseVideoView.java:873)
>                                                                                                     	at com.brightcove.player.view.BaseVideoView.showMediaController(BaseVideoView.java:866)
>                                                                                                     	at com.brightcove.player.view.BaseVideoView.toggleMediaControlsVisibility(BaseVideoView.java:847)
>                                                                                                     	at com.brightcove.player.view.BaseVideoView.onTouchEvent(BaseVideoView.java:329)
>                                                                                                     	at android.view.View.dispatchTouchEvent(View.java:14309)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3112)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2785)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter_androidKt$pointerInteropFilter$3.invoke(PointerInteropFilter.android.kt:113)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter_androidKt$pointerInteropFilter$3.invoke(PointerInteropFilter.android.kt:105)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1$dispatchToView$3.invoke(PointerInteropFilter.android.kt:301)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1$dispatchToView$3.invoke(PointerInteropFilter.android.kt:294)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropUtils_androidKt.toMotionEventScope-ubNVwUQ(PointerInteropUtils.android.kt:81)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropUtils_androidKt.toMotionEventScope-d-4ec7I(PointerInteropUtils.android.kt:35)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1.dispatchToView(PointerInteropFilter.android.kt:294)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1.onPointerEvent-H0pRuoY(PointerInteropFilter.android.kt:229)
>                                                                                                     	at androidx.compose.ui.node.BackwardsCompatNode.onPointerEvent-H0pRuoY(BackwardsCompatNode.kt:394)
>                                                                                                     	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:296)
>                                                                                                     	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:301)
>                                                                                                     	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:183)
>                                                                                                     	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:102)
>                                                                                                     	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:98)
>                                                                                                     	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1329)
>                                                                                                     	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:1275)
> 2023-05-15 15:00:37.530 17103-17103 AndroidRuntime          com...ayer.samples.compose.activity  E  	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:1214)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
>                                                                                                     	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
>                                                                                                     	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
>                                                                                                     	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
>                                                                                                     	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
>                                                                                                     	at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
>                                                                                                     	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
>                                                                                                     	at android.view.View.dispatchPointerEvent(View.java:14568)
>                                                                                                     	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
>                                                                                                     	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>                                                                                                     	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>                                                                                                     	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
>                                                                                                     	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
>                                                                                                     	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
>                                                                                                     	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
>                                                                                                     	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
>                                                                                                     	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
>                                                                                                     	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
>                                                                                                     	at android.os.MessageQueue.nativePollOnce(Native Method)
>                                                                                                     	at android.os.MessageQueue.next(MessageQueue.java:335)
>                                                                                                     	at android.os.Looper.loop(Looper.java:183)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:7656)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
> 2023-05-15 15:00:37.532   559-1642  ActivityTaskManager     system_server                        W    Force finishing activity com.brightcove.player.samples.compose.activity/.MainActivity

**Comment by Azizkhuja** [comment]
@fllaryora Did you manage to fix this error?

**Comment by fllaryora** [comment]
@Azizkhuja No, I didn't.
