### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'android.media.session.ISessionController 

### ISSUE THREAD

**Issue by MithilMehta-TUL-Luxury** [BrightcoveOS/android-player-samples#285]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.media.session.ISessionController android.media.session.ISession.getController()' on a null object reference
                                  	at android.media.session.MediaSession.<init>(MediaSession.java:207)
                                  	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi29.createFwkMediaSession(MediaSessionCompat.java:4457)
                                  	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi21.<init>(MediaSessionCompat.java:3821)
                                  	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi22.<init>(MediaSessionCompat.java:4405)
                                  	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi28.<init>(MediaSessionCompat.java:4422)
                                  	at android.support.v4.media.session.MediaSessionCompat$MediaSessionImplApi29.<init>(MediaSessionCompat.java:4447)
                                  	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:576)
                                  	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:539)
                                  	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:503)
                                  	at android.support.v4.media.session.MediaSessionCompat.<init>(MediaSessionCompat.java:477)
                                  	at com.brightcove.player.playback.ExoMediaPlayback.<init>(ExoMediaPlayback.java:838)
                                  	at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.createPlayback(ExoPlayerVideoDisplayComponent.java:263)
                                  	at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.onCreatePlayback(ExoPlayerVideoDisplayComponent.java:252)
                                  	at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.onCreatePlayback(ExoPlayerVideoDisplayComponent.java:94)
                                  	at com.brightcove.player.display.VideoDisplayComponent.<init>(VideoDisplayComponent.java:177)
                                  	at com.brightcove.player.display.ExoPlayerVideoDisplayComponent.<init>(ExoPlayerVideoDisplayComponent.java:242)
                                  	at com.brightcove.player.view.BrightcoveExoPlayerVideoView.createVideoDisplayComponent(BrightcoveExoPlayerVideoView.java:79)
                                  	at com.brightcove.player.view.BaseVideoView.setEventEmitter(BaseVideoView.java:482)
                                  	at com.brightcove.player.view.BaseVideoView.finishInitialization(BaseVideoView.java:414)
                                  	at com.brightcove.player.view.BaseVideoView.onFinishInflate(BaseVideoView.java:403)
                                  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1158)
                                  	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
                                  	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1148)
                                  	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1106)
                                  	at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
                                  	at android.view.LayoutInflater.inflate(LayoutInflater.java:544)
                                  	at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
                                  	at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1409)

**Comment by jrw95** [comment]
Hi @MithilMehta-TUL-Luxury , can you provide more context around this error?
What sample app(s) are you seeing this with?
What steps are you following to reproduce this?

**Comment by nandovelazquez** [comment]
We are closing the Issues feature for this repo next month. If your problem persists, please report it as an issue through our support page: https://sdks.support.brightcove.com/developer-support/questions/report-issue-brightcove-native-sdks.html
